//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDOperations
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int SId { get; set; }
        public string SName { get; set; }
        public string SAddress { get; set; }
        public int Class { get; set; }
        public int Id { get; internal set; }
        public string Name { get; internal set; }
        public string Address { get; internal set; }
    }
}
